title: Log Blog Kebab
author: Steve Dignam
description: >-
  A blog about software and everything that goes with it. Ideally
  informative.
permalink: pretty
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://steve.dignam.xyz"
github_username:  sbdchd
rss: "rss"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - examples/
