permalink:        pretty
relative_permalinks: true

title:            Stev
tagline:          A blog of things.
description:	  A blog of many things. Mostly technology.
url:              http://steve.dignam.xyz
paginate:         20
baseurl:          /
gems:
  - jekyll-sitemap

markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]

author:
  name:           Steve
  url:            https://steve.dignam.xyz
  email:          mail@dignam.xyz
  alt_contact: 	  https://plus.google.com/u/0/+StephenDignam/
  profile_photo:  /public/sloth_899x600.jpg

github: https://github.com/sbdchd

pages_list:
  About: '/about/'

